name: kvant_medpuls
description: "Квант.МедПульс"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  equatable: ^2.0.5
  http: ^1.5.0
  formz: ^0.8.0
  intl: 0.20.2
  dio: ^5.4.0
  get_it: ^8.2.0
  shared_preferences: ^2.2.3
  web_socket_channel: ^3.0.0
  flutter_secure_storage: ^9.2.4
  universal_html: ^2.2.1
  signature: ^6.3.0
  printing: ^5.14.2
  pdf: ^3.11.3
  path_provider: ^2.1.5
  syncfusion_flutter_pdfviewer: ^30.2.7
  url_launcher: ^6.1.10
  provider: ^6.1.5+1
  open_file: ^3.5.10
  http_parser: ^4.1.2
  image: ^4.5.4
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

# Flutter-specific configuration
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Roboto-Regular.ttf
    - lib/core/assets/icon.png
    - lib/core/assets/logo.svg


flutter_icons:
  android: true
  ios: true
  image_path: "lib/core/assets/icon.png"
  adaptive_icon_background: "#5F9EA0"
  adaptive_icon_foreground: "lib/core/assets/icon.png"